### ISSUE TITLE
goreportcard-cli not working

### ISSUE THREAD

**Issue by Strachi-sama** [gojp/goreportcard#362]
```bash
panic: runtime error: index out of range [1] with length 1

goroutine 8 [running]:
github.com/gojp/goreportcard/check.fileURL({0x10e5ca7, 0x1}, {0xc0003b6000, 0x1})
        /Users/user/goreportcard/check/utils.go:231 +0x868
github.com/gojp/goreportcard/check.getFileSummaryMap(0xc000079cb0, {0x10e5ca7, 0x1})
        /Users/user/goreportcard/check/utils.go:303 +0x175
github.com/gojp/goreportcard/check.GoTool({0x10e5ca7, 0x0}, {0xc00010e200, 0x1e, 0x0}, {0xc00005ed80, 0x0, 0x6})
        /Users/user/goreportcard/check/utils.go:362 +0x458
github.com/gojp/goreportcard/check.GoLint.Percentage({{0x10e5ca7, 0x1}, {0xc00010e200, 0x1e, 0x20}})
        /Users/user/goreportcard/check/golint.go:21 +0x138
github.com/gojp/goreportcard/check.Run.func1({0x110ce18, 0xc000066210})
        /Users/user/goreportcard/check/check.go:70 +0x4b
created by github.com/gojp/goreportcard/check.Run
        /Users/user/goreportcard/check/check.go:69 +0x7af
```

**Comment by shawnps** [comment]
@Strachi-sama I'm not able to reproduce this issue locally -- could you provide a public repo that causes this issue? Thanks

**Comment by joao-fontenele** [comment]
I'm having the same issue, git bisect tells me it's this commit that introduced the error https://github.com/gojp/goreportcard/commit/7455924850b0aeee63881d32c41cfe1fc7ef1bb8

**Comment by shawnps** [comment]
1237c87 may have fixed it, please try again

**Comment by Strachi-sama** [comment]
```bash
Users-iMac:~ user$ rm -rf goreportcard/
Users-iMac:~ user$ git clone https://github.com/gojp/goreportcard.git
Cloning into 'goreportcard'...
remote: Enumerating objects: 6062, done.
remote: Counting objects: 100% (2574/2574), done.
remote: Compressing objects: 100% (1270/1270), done.
remote: Total 6062 (delta 1335), reused 2344 (delta 1175), pack-reused 3488
Receiving objects: 100% (6062/6062), 10.06 MiB | 13.33 MiB/s, done.
Resolving deltas: 100% (3177/3177), done.
Users-iMac:~ user$ cd goreportcard
Users-iMac:goreportcard user$ make install
./scripts/make-install.sh
Users-iMac:goreportcard user$ go install ./cmd/goreportcard-cli
Users-iMac:goreportcard user$ goreportcard-cli
-bash: goreportcard-cli: command not found
```
It works perfectly on Goland, I guess it's something path related. Thank you
